spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.PostgreSQL10Dialect

    show-sql: true

#spring:
#  h2:
#    console.enabled: true